#include "gpio.h"

//Pin values configurations 

gpio_Configurations_t portsCfgs={
	//PORTA
	{{{
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_ENABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_ENABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_ENABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}}}
	
	//PORTB
	,{{

	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}
	}
}
	//PORTC
	,{{
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}
}}
	//PORTD
,{
	{
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}
}
	}
	//PORTE
	
	,{{
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_ANALOG,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_ENABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
 	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}
	}}
	
	//PORTF
	,{{
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_OUTPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE},
	
	{GPIO_MODE_DIGITAL,
  GPIO_DIR_INPUT,
	GPIO_DISABLE,
	GPIO_DISABLE,
	GPIO_DISABLE}
	

}
	}}
};
